spring:

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        show_sql: true

  datasource:
    url: jdbc:postgresql://${PICKDATE_DATABASE_URL:localhost:5432/pickdate}
    username: ${PICKDATE_DATABASE_USER:root}
    password: ${PICKDATE_DATABASE_PASS:pass}
    name: pickdate
    hikari:
      maximum-pool-size: 20

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true

# override observability config
pickdate:
  observability:
    problem:
      enabled: true
      logged-statuses: [ 400, 401, 403, 404, 409, 500, 503 ]
    audit:
      enabled: true
